// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5a7-NNhNDSIzwH_MmQi9k4qgyh4Xwzyw',
    appId: '1:980077470828:web:e396a7fe56738a6d896449',
    messagingSenderId: '980077470828',
    projectId: 'travel-guide-42552',
    authDomain: 'travel-guide-42552.firebaseapp.com',
    storageBucket: 'travel-guide-42552.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZzbvSvbYdnj3NtA9OcmwetPtBZ7uHIk0',
    appId: '1:980077470828:android:cb13fc26f42ca17e896449',
    messagingSenderId: '980077470828',
    projectId: 'travel-guide-42552',
    storageBucket: 'travel-guide-42552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6nDkFkGtsdFEV_loMxjlos24owmAbVY',
    appId: '1:980077470828:ios:3b6cfb22c9c78ec4896449',
    messagingSenderId: '980077470828',
    projectId: 'travel-guide-42552',
    storageBucket: 'travel-guide-42552.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6nDkFkGtsdFEV_loMxjlos24owmAbVY',
    appId: '1:980077470828:ios:3b6cfb22c9c78ec4896449',
    messagingSenderId: '980077470828',
    projectId: 'travel-guide-42552',
    storageBucket: 'travel-guide-42552.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5a7-NNhNDSIzwH_MmQi9k4qgyh4Xwzyw',
    appId: '1:980077470828:web:77e70d812c5b58f0896449',
    messagingSenderId: '980077470828',
    projectId: 'travel-guide-42552',
    authDomain: 'travel-guide-42552.firebaseapp.com',
    storageBucket: 'travel-guide-42552.appspot.com',
  );
}
